PelionIoT/meta-pelion-edge

- recipes-wigwag/global-node-modules/global-node-modules_0.0.1.bb
Will move to dev branch after 2.0.0 release
> sets global-node-modules to autorev

- recipes-wigwag/devicedb/devicedb_0.0.12.bb
This corrects a build error on the current master as of
https://github.com/armPelionEdge/devicedb/pull/1
> Update DeviceDB GO_IMPORT

- BUILD.md
Syntax changes to make following the instructions not require vertical scroll bars...
> Update BUILD.md for better readability

- recipes-wigwag/mbed-edge-core/files/rpi3/arm_update_activate.sh
+ Use systemd cmds to manage processes
> PELEDGE19-934 Use systemd cmds to start/stop processes

- recipes-wigwag/mbed-edge-core/mbed-edge-core.inc
Product requirement to use latest edge-core
> Upgraded mbed-edge version to latest release 0.10.0

- recipes-wigwag/maestro/maestro/maestro.service
- recipes-wigwag/maestro/maestro_0.0.1.bb
Reverts armPelionEdge/meta-pelion-edge#110
> Revert "Updated maestro SHA to test the memory leak fixes"

- BUILD.md
- FLASH.md
- README.md
Migrating the README changes made on dev branch to master. This also fixes the broken links mentioned in the readme of master branch.
> Updating master branch README

- recipes-extended/cronie/cronie/crontab
- recipes-wigwag/wwrelay-utils/wwrelay-utils_1.0.1.bb
This is no longer needed as memory leak in maestro has been fixed
> Removed the midnight restart of gateway services

- BUILD.md
- CONTRIBUTING.md
- FLASH.md
- README.md
1. Corrected the dd commands for both MAC OS X and Linux
2. Updated README to direct user to manifest-pelion-edge if they are
looking for a simple guide to build the image.
3. Added Contributing.md
> Updated README

- recipes-wigwag/wwrelay-utils/wwrelay-utils_1.0.1.bb
Derive the edge addresses based on new CoAP addresses
> Updated edge-utils SHA

- CHANGELOG.md
Cherry pick'd changelog change to make sure `master` and `dev` do not diverge.
> Edit CHANGELOG.md

- CHANGELOG.md
- recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
Fixed python depenency issue preventing build to complete.
> Release 2.1.1

- recipes-wigwag/edge-proxy/files/launch-edge-proxy.sh
1. Added gateways.local to the host file as edge proxy listens for the HTTP request from gateway services on that hostname.
2. Added deviceID to the host file for devicedb.
> Append /etc/hosts with gateway.local and deviceID in edge-proxy unit file

- recipes-wigwag/maestro/maestro/rpi3/maestro-config-rpi3bplus.yaml
1. Added gateway_capabilites config - registring kaas, fluentbit and terminal
1. Removed Node references
1. Disabled watchdog service as its no longer supported
> Updated RPi maestro configuration

- recipes-extended/logrotate/files/varlog
- recipes-extended/logrotate/logrotate_%.bbappend
Have manually build and verified this on a dev build.
> Added varlog conf file to rotate the log files in /var/log/*

- recipes-core/images/console-image.bb
Introduces independent recipes of similar function.
> updates the console-image to remove wwrelay-utils

- recipes-extended/fluentbit/files/td-agent-bit.conf
- recipes-wigwag/maestro/maestro/imx8mmevk/maestro-config-imx8mmevk.yaml
- recipes-wigwag/maestro/maestro/rpi3/maestro-config-rpi3bplus.yaml
- recipes-wigwag/maestro/maestro/uz3eg/maestro-config-uz3eg.yaml
Renamed devicejs.log to maestro_gw.log in maestro.conf for all platforms. Also updated the fluentbit conf file. 
This is an effort towards phasing out devicejs.
> Renamed the log file generated by maestro logging system

- recipes-containers/kubelet/files/kubelet.service
- recipes-extended/fluentbit/files/td-agent-bit.service
- recipes-wigwag/edge-proxy/files/edge-proxy.service
- recipes-wigwag/maestro/maestro/maestro.service
- recipes-wigwag/relay-term/files/pelion-relay-term.service
this will stop the services from starting and constantly dumping logs on disk when the gateway is not provisioned.
> Added ExecCondition in service unit files to stop the services from starting until the gateway is provisioned

- recipes-wigwag/maestro/maestro/imx8mmevk/0003-build-with-autoconf.patch
- recipes-wigwag/maestro/maestro/rpi3/0003-build-with-autoconf.patch
- recipes-wigwag/maestro/maestro/uz3eg/0003-build-with-autoconf.patch
Reverts PelionIoT/meta-pelion-edge#244
> Revert "Updated maestro patch to work with latest maestro version"

- meta-lmp-support/recipes-bsp/u-boot/u-boot-fio/imx8mmevk/0001-Disable-1V8-on-usdhc2-for-SDMUX.patch
- meta-lmp-support/recipes-bsp/u-boot/u-boot-fio_%.bbappend
- meta-lmp-support/recipes-connectivity/networkmanager/files/addr_gen_mode_eui64.patch
- meta-lmp-support/recipes-connectivity/networkmanager/networkmanager_%.bbappend
- meta-lmp-support/recipes-kernel/linux/files/0001-Disable-1V8-on-usdhc2-for-SDMUX-kernel.patch
- meta-lmp-support/recipes-kernel/linux/linux-lmp-fslc-imx_git.bbappend
These patches add some extra support for the imx8 board and IPv6
> Extra support patches

- CHANGELOG.md
Document the known issue with stability regarding the Xilinx kernel
configurations.
> CHANGELOG - Xilinx ZU3EG kernel config limitations

- meta-lmp-support/recipes-core/images/console-image-lmp.bb
- recipes-core/images/console-image.bb
Updated the image recipes to create a parsec user.
Change permissions on parsec related files to be accesible to the new
parsec user.
> Change to run parsec as the parsec user.

- meta-lmp-support/conf/machine/include/lmp-factory-custom.inc
- meta-lmp-support/recipes-core/base-files/base-files/imx8mmevk/fstab
- meta-lmp-support/recipes-core/base-files/base-files/rpi/fstab
- meta-lmp-support/recipes-core/base-files/base-files/uz/fstab
- meta-lmp-support/wic/sdimage-imx8-spl-sota-config.wks.in
- meta-lmp-support/wic/sdimage-rpi3-spl-sota-config.wks.in
- meta-lmp-support/wic/sdimage-uz-spl-sota-config.wks.in
Removed all of the unused partitions.
> Simplify partition layout.

- recipes-wigwag/edge-proxy/edge-proxy_git.bb
> allow yocto QA to pass

- meta-lmp-support/conf/machine/include/lmp-factory-custom.inc
- recipes-bsp/bootfiles/rpi-config_git.bbappend
this seems to pass now, so lets use this approach as it is better to just got with standard settings with minimal modifications.
> [BLE]just use standard console and ble settings

- CHANGELOG.md
This is a very first draft of the changelog. I have tried capturing all the updated we made through the PRs in various project in this release. I have marked TBC (To be concluded) for the items I don't know much about. Please review and update the statements for the features you worked on.
> Changelog 2.4

- meta-lmp-support/files/pelion-group-table
- meta-lmp-support/files/pelion-passwd-table
- meta-lmp-support/recipes-core/images/console-image-lmp.bb
- recipes-extended/deviceos-users/deviceos-users_0.0.1.bb
New LmP requires static UID/GID defined for added users
> Lmp 82 update

- docs/bring_up_pc_ble_driver.md
- recipes-connectivity/pc-ble-driver/pc-ble-driver_4.1.4.bb
Add a recipe to build pc-ble-driver and wire it into the build.
> Add PC-BLE-driver (for NRF chips)

- meta-lmp-support/conf/machine/include/lmp-factory-custom.inc
- meta-lmp-support/recipes-core/images/console-image-lmp.bb
- meta-lmp-support/recipes-security/softhsm/softhsm/tmpfiles.conf
- meta-lmp-support/recipes-security/softhsm/softhsm_2.%.bbappend
Updated the RPi devices to use the SOFTHSM instead of SOFTWARE_TPM.
> Add support for softhsm.

- meta-lmp-support/recipes-core/images/console-image-lmp-stress.bb
Internal references.
https://armiot.atlassian.net/browse/IOTNGGW-313
https://armiot.atlassian.net/browse/IOTNGGW-314
> adds an image void of Pelion software with stress and development tools

- recipes-core/systemd/systemd_%.bbappend
> Remove systemd-resolved

- recipes-containers/kube-router/files/launch-kube-router.sh
- recipes-containers/kubelet/files/launch-kubelet.sh
Make kubelet use the same CNI config as kube-router.
> Fix kubelet and kube-router use same CNI conf

- recipes-wigwag/mbed-fcce/mbed-fcce_4.11.1.bb
Changed to use mbed-tools instead of mbed-cli.
> Fix fcce build

- meta-lmp-support/recipes-core/images/console-image-lmp.bb
- recipes-core/images/console-image.bb
- recipes-misc/testnet/testnet_2.0.0.bb
For means to troubleshoot/verify the connections do not get blocked by a firewall.
https://github.com/PelionIoT/pe-utils/tree/master/fw-tools
Ref: IZUMABL-200
> Add recipe for pe-utils/fw-tools/testnet.sh (v 2.0.11)

- recipes-connectivity/identity-tool/identity-tool_0.0.1.bb
- recipes-misc/info-tool/info-tool_2.0.0.bb
It's still pointing at the legacy domain.
> Update identity-tool domain (PelionIoT)
