.gitignore, recipes-wigwag/deviceOSWD/deviceoswd_0.0.2.bb, recipes-wigwag/maestro/maestro/maestro.service, recipes-wigwag/maestro/maestro_0.0.1.bb, recipes-wigwag/mbed-edge-core/files/edge-core.service, recipes-wigwag/mbed-edge-core/mbed-edge-core.inc, recipes-wigwag/wwrelay-utils/wwrelay-utils_1.0.1.bb
Components enabled so far:
name it something else)
=> Enable systemd services for Pelion Edge components

recipes-wigwag/maestro/maestro/maestro.service
Previously, maestro.service required deviceos-wd.service. This
creates an untracked dependency between `maestro` and `deviceos-wd`.
After some experimentation, we found that maestro does not need
a running deviceos-wd to start correctly. This commit breaks this
untracked dependency and allows another development board to boot,
as it does not have a working watchdog.
=> Allow Maestro to start without deviceos-wd

recipes-wigwag/devicedb/devicedb_0.0.12.bb
Perviously, devicedb would build with `-linkshared` and that would
cause it to panic with `fatal error: sweep increased allocation count`.
This commit works around the issue by removing `-linkshared`
Implementation notes: This uses the `GO_LINKSHARED` vairable within the
bitbake class.
=> Drop `-linkshared` from devicedb build

recipes-wigwag/wwrelay-utils/wwrelay-utils_1.0.1.bb
A script in edge-utils, called by the wait-for-pelion-identity service
depends on the installation of global-node-modules. This codifies that
information.
=> Depend on global-node-modules

recipes-wigwag/maestro/maestro_0.0.1.bb
greaselib compiled code not seen by the yocto builtin inherited class.  Also inherited class is not properly quoting "GO_EXTLDFLAGS" when adding buildmode=pie.
=> Fixes greaselib path not found

conf/layer.conf
Local builds started failing yesterady with the following error:
`ERROR: Layer meta-rpi is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)`
~No CI builds appear to be affected _yet_, but I was unable to find one that has run successfully within the last couple of days.~ Nvm, seems that Yash already ran into problems.
=> Added 'warrior' as an additional compatible layer to meta-pelion-edge.

recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
`pip` v20.x.x has been causing dependency issues this weeks.
This PR pins `pip` to the last major version after it's been installed.
=> mbed-fcc fix

recipes-wigwag/maestro/maestro/maestro.service, recipes-wigwag/maestro/maestro_0.0.1.bb
1. This SHA has fixes to the memory leak
2. Updated maestro.service to start the process with madvdontneed Go env flag.
=> Updated maestro SHA to test the memory leak fixes

recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
mbed-fcc fails to install with latest pip version. Thus v1.0.0 of meta-pelion-edge is broken currently. This PR will fix the release.
=> Added pip install step to pin pip to an older version

recipes-wigwag/maestro/maestro/maestro.service
Please refer these tickets to understand why this runtime flag is being added
https://jira.arm.com/browse/PELEDGE19-1336
https://jira.arm.com/browse/PELEDGE19-1334
=> maestro: Adding go runtime flag - madvdontneed to service file

recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
Recent update to click python module broke the mbed-fcc. Locked the click
version to 7.0. This fixes the bug - https://jira.arm.com/browse/PELEDGE19-2493
=> Locking the click version fixes the 1.0.1 release of meta-pelion-edge

recipes-core/glibc/files/gai.conf, recipes-core/glibc/glibc_2.%.bbappend
More info - http://man7.org/linux/man-pages/man5/gai.conf.5.html
Observation: By default, the sorting algorithm used by getaddrinfo defined by RFC 3484 prioritizes IPv6 address over IPv4. In the scenario, where multiple addresses are resolved on calling getaddrinfo, PE gateway fails to reach Internet using IPv6 address. That can happen if NAT is not configured to handle IPv6. As IPv4 is more prominent and most networks are configured to
correctly route IPv4 addresses thus gateway should first talk over IPv4 vs IPv6.
=> Introducing gai.conf to priortize IPv4 address over IPv6

recipes-core/images/console-image.bb, recipes-wigwag/relay-term/files/pelion-relay-term.service
Adding relay term service on the gateway. This enables the remote terminal feature from Pelion cloud.
=> Enabling relay-term service

recipes-wigwag/maestro/maestro/maestro.service
This avoids a race where devicejs (a process started by maestro)
creates the `/userdata/etc/` directory, that maestro requires
concurrently. Instead, I added a step before starting maestro
that creates this directory.
=> Work around segfault in Maestro

recipes-wigwag/maestro/maestro/maestro-watcher.path, recipes-wigwag/maestro/maestro/maestro-watcher.service, recipes-wigwag/maestro/maestro_0.0.1.bb
With path units, you can monitor files and directories for events and use them to execute service units. Added path file to monitor identity.json and call service unit which will restart maestro service. Once the gateway has been claimed, maestro needs to be restarted to consume the new identity and create config files for other gateway services.
=> Use path unit to monitor the change in identity file to restart maestro

recipes-wigwag/maestro/maestro-rpi3.bb, recipes-wigwag/maestro/maestro/maestro.service, recipes-wigwag/maestro/maestro/rpi3/devicedb.template.conf, recipes-wigwag/maestro/maestro/rpi3/devicejs.template.conf, recipes-wigwag/maestro/maestro/rpi3/maestro-config-rpi3bplus.yaml, recipes-wigwag/maestro/maestro/rpi3/radioProfile.template.json, recipes-wigwag/maestro/maestro/rpi3/relayTerm.template.json, recipes-wigwag/maestro/maestro_0.0.1.inc
As the services' configurations are platform dependent and maestro
is tasked to generate configuration for all gw services, thus relocating
the template files from edge-utils to meta-pe/maestro recipe.
=> Adding gateway services' templates and maestro config for RPi3

recipes-wigwag/relay-term/files/relay-term-watcher.path, recipes-wigwag/relay-term/files/relay-term-watcher.service, recipes-wigwag/relay-term/relay-term_0.0.1.bb
When identity.json is written, maestro will generate configuration file for
gateway services and also write device certificates to file. Monitor the
device certificate and restart relay-term if it changes.
=> Monitor device client certificate, on change restart relay-term

recipes-core/init-ifupdown/files/interfaces
Reverts armPelionEdge/meta-pelion-edge#121
The whitespace was the correct syntax. More info - https://www.cyberciti.biz/faq/setting-up-an-network-interfaces-file/
=> Revert "Removed whitespaes from interfaces file"

conf/layer.conf
After testing the clean build without meta-mbl layers #128 and with yocto warrior, it
is observed that the RPi is not booting. When I tested the same with thud it seems to
be working. Internal ticket has been created to upgrade the yocto version to Dunfell in
the next release.
=> Reverting to thud as with warrior, RPi is not booting

recipes-wigwag/relay-term/files/relay-term-watcher.path
Unit file name was misspelled in the path unit file
=> Fixed relay-term not restarting after identity.json change

conf/bblayers.conf.sample
More information - https://www.yoctoproject.org/docs/3.1.1/ref-manual/ref-manual.html#structure-build-conf-bblayers.conf
=> Yocto uses sed to substitute final ${OEROOT} values for all ##OEROOT## values.

README.md
The link in the README.md has not been updated yet. The new docs are at staging and
waiting for 2.0 to be merged to master. This doc have been migrated to
[internal docs repos](https://github.com/ARMmbed/pelion-dm-edge-docs/blob/master/docs/quick-start.md).
=> Migrated the content to the public docs

recipes-core/images/console-image.bb, recipes-core/netbase/netbase/hosts, recipes-core/netbase/netbase_%.bbappend, recipes-wigwag/edge-proxy/edge-proxy_git.bb, recipes-wigwag/edge-proxy/files/edge-proxy-watcher.service, recipes-wigwag/edge-proxy/files/edge-proxy.conf.json, recipes-wigwag/edge-proxy/files/edge-proxy.path, recipes-wigwag/edge-proxy/files/edge-proxy.service, recipes-wigwag/edge-proxy/files/launch-edge-proxy.sh, recipes-wigwag/maestro/maestro/rpi3/devicejs.template.conf
Adds edge-proxy to console-image
sets 127.0.0.1		gateways.local in /etc/init.d in preparation for kubelet tunneling
Compiles and installs edge-proxy & associated systemd units with separate launcher script
Modifies devicejs config to use port 8081 as 8080 is needed by edge-kubelet
=> adds edge-proxy service in preparation for kubelet and docker

conf/bblayers.conf.sample, conf/local.conf.sample, recipes-containers/docker/docker_%.bbappend, recipes-containers/docker/files/daemon.json, recipes-containers/kubelet/files/10-c2d.conf, recipes-containers/kubelet/files/99-loopback.conf, recipes-containers/kubelet/files/kubeconfig, recipes-containers/kubelet/files/kubelet-config.yaml, recipes-containers/kubelet/files/kubelet-watcher.service, recipes-containers/kubelet/files/kubelet.path, recipes-containers/kubelet/files/kubelet.service, recipes-containers/kubelet/files/launch-edgenet.sh, recipes-containers/kubelet/files/launch-kubelet.sh, recipes-containers/kubelet/kubelet_git.bb, recipes-core/images/console-image.bb, recipes-core/netbase/netbase/hosts, recipes-core/netbase/netbase_%.bbappend, recipes-kernel/linux/linux-raspberrypi_%.bbappend, recipes-networking/cni/cni_git.bb, recipes-networking/cni/files/c2d, recipes-networking/cni/files/c2d-inner, recipes-wigwag/edge-proxy/edge-proxy_git.bb, recipes-wigwag/edge-proxy/files/edge-proxy-watcher.service, recipes-wigwag/edge-proxy/files/edge-proxy.conf.json, recipes-wigwag/edge-proxy/files/edge-proxy.path, recipes-wigwag/edge-proxy/files/edge-proxy.service, recipes-wigwag/edge-proxy/files/launch-edge-proxy.sh, recipes-wigwag/maestro/maestro/rpi3/devicejs.template.conf
Big pull request brings in several files to enable container orchestration.
=> Dev 2.1 add containers

recipes-wigwag/deviceOSWD/deviceoswd_0.0.2.bb, recipes-wigwag/devicedb/devicedb_0.0.12.bb, recipes-wigwag/devicejs/devicejs_0.0.12.bb, recipes-wigwag/edge-proxy/edge-proxy_git.bb, recipes-wigwag/global-node-modules/global-node-modules_0.0.1.bb, recipes-wigwag/isc-dhclient/isc-dhclient_1.0.bb, recipes-wigwag/maestro-shell/maestro-shell_0.0.1.bb, recipes-wigwag/maestro-watchdog/maestro-watchdog_0.0.1.bb, recipes-wigwag/maestro/maestro_0.0.1.inc, recipes-wigwag/mbed-devicejs-bridge/mbed-devicejs-bridge_0.0.1.bb, recipes-wigwag/mbed-edge-core/mbed-edge-core.inc, recipes-wigwag/mbed-edge-examples/mbed-edge-examples.bb, recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb, recipes-wigwag/node-6lbr/node-6lbr_1.0.bb, recipes-wigwag/node-hotplug/node-hotplug_1.0.bb, recipes-wigwag/node-netkit/node-netkit_1.0.bb, recipes-wigwag/node-znp/node-znp_1.0.bb, recipes-wigwag/strace-plus/strace-plus_1.0.bb, recipes-wigwag/tsb/tsb_0.0.1.bb, recipes-wigwag/wwrelay-utils/wwrelay-utils_1.0.1.bb
Some customers has reported that they are  unable to build meta-pelion-edge
as their corporate firewall only allows outbound HTTP/HTTPS but not SSH. This
should help with that use case.
Also updated SHAs of devicejs-ng and global-node-modules as they were internally referring to ssh links.
=> HTTPS is less likely to be blocked by a firewall

CHANGELOG.md, recipes-wigwag/deviceOSWD/deviceoswd_0.0.2.bb, recipes-wigwag/devicedb/devicedb_0.0.12.bb, recipes-wigwag/devicejs/devicejs_0.0.12.bb, recipes-wigwag/edge-proxy/edge-proxy_git.bb, recipes-wigwag/global-node-modules/global-node-modules_0.0.1.bb, recipes-wigwag/isc-dhclient/isc-dhclient_1.0.bb, recipes-wigwag/maestro-shell/maestro-shell_0.0.1.bb, recipes-wigwag/maestro-watchdog/maestro-watchdog_0.0.1.bb, recipes-wigwag/maestro/maestro_0.0.1.inc, recipes-wigwag/mbed-devicejs-bridge/mbed-devicejs-bridge_0.0.1.bb, recipes-wigwag/mbed-edge-core/mbed-edge-core.inc, recipes-wigwag/mbed-edge-examples/mbed-edge-examples.bb, recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb, recipes-wigwag/node-6lbr/node-6lbr_1.0.bb, recipes-wigwag/node-hotplug/node-hotplug_1.0.bb, recipes-wigwag/node-netkit/node-netkit_1.0.bb, recipes-wigwag/node-znp/node-znp_1.0.bb, recipes-wigwag/strace-plus/strace-plus_1.0.bb, recipes-wigwag/tsb/tsb_0.0.1.bb, recipes-wigwag/wwrelay-utils/wwrelay-utils_1.0.1.bb
This will build meta-pelion-edge in the environment where only outbound HTTP/HTTPS is allowed by a firewall.
=> Release 2.1.0-1 - Updated package source file protocol from ssh to https.

recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
Experienced an issue similar to this one after the python module was updated to v20.0.0:
https://github.com/pypa/pipenv/issues/4548#issuecomment-735992788
Without this pin, building against the 'dev' branch is currently broken.
CI build link incoming once it completes, but have verified on my local system that this seems to resolve the problem.
=> Pinned version of 'pyopenssl' for 'mbed-fcc' recipe.

recipes-wigwag/devicedb/devicedb_0.0.12.bb, recipes-wigwag/maestro/maestro/rpi3/devicedb.template.conf, recipes-wigwag/maestro/maestro/rpi3/devicejs.template.conf, recipes-wigwag/maestro/maestro/rpi3/maestro-config-rpi3bplus.yaml, recipes-wigwag/maestro/maestro/rpi3/relayTerm.template.json, recipes-wigwag/maestro/maestro_0.0.1.inc
Changing Devicedb, ~Devicejs~, Relay-term, maestro config so that all services on raspberry Pi can talk through edge-proxy.
Tested functionality of relay-term, maestro by running edge-proxy on raspberry Pi.
~Needs further testing when edge-proxy is added to the meta-pelion-edge repo.~
=> Modified services and configs to re-route traffic through edge-proxy

conf/bblayers.conf.sample, recipes-core/images/console-image.bb, recipes-wigwag/relay-term/files/npm-shrinkwrap.json, recipes-wigwag/relay-term/files/pelion-relay-term.service, recipes-wigwag/relay-term/files/relay-term-watcher.path, recipes-wigwag/relay-term/relay-term_0.0.1.bb
Also added shrinkwrap.json as its required to successfully build the package. npm-shrinkwrap.json is also part of the relay-term source code, but was not able to use that so had to add it here.
=> Relay-term: Removed meta-nodejs, use yocto's native nodejs, removed dependency on global-node-modules

recipes-connectivity/identity-tool/files/wait-for-pelion-identity.service, recipes-containers/kubelet/files/kubelet.service, recipes-extended/fluentbit/files/td-agent-bit.service, recipes-wigwag/edge-proxy/files/edge-proxy.service, recipes-wigwag/maestro/maestro/maestro.service, recipes-wigwag/relay-term/files/pelion-relay-term.service
According to https://www.freedesktop.org/software/systemd/man/systemd.unit.html, `Requires` builds a stronger dependency vs `Wants`. For instance, currently we "requires" edge-core in wait-for-pelion-identity. So if edge-core restarts, wait-for-pelion-identity is stopped and restarted by systemd. And as other services also requires wait-for-pelion-identity, edge-proxy is stopped and restarted, similarly maestro, kubelet and relay-term. 
So I ran into this scenario where maestro started crashing edge-core (due to version mismatch) and as edge-core restarted, everything restarted and maestro again crashed edge-core and so on.. the dormammu time loop.. 
In order to break this cyclic dependeny, the proposal is to use `Wants`, that way even though the service is crashed, it wont force the …
=> Streamlined the startup sequence inorder to remove the cyclic dependency

recipes-core/systemd/systemd-conf%.bbappend, recipes-core/systemd/systemd-conf/00-systemd-conf.conf
sed doesn't work as the [original file](http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd-conf/journald.conf?h=dunfell&id=d87efd14ce0471135c0aa7fd7b5da2808acb9c76) do not contains the search strings. Adding a file which overwrites the default file.
=> systemd-conf - add the flags in journal.conf for FSS feature

recipes-misc/path-set/path-set_0.0.1.bb, recipes-misc/pelion-version/pelion-version_0.0.1.bb
Fix license names to "Apache-2.0". It was written as "APACHE-2.0", which was unrecognized and yielding build warnings in Yocto.
=> Fix license names to Apache-2.0

recipes-containers/kubelet/kubelet_git.bb
This will fix the Argus's kubelet version bug.
=> Kubelet - removed the patch to version.sh as bash is added to DEPEDNS

conf/local.conf.sample
Have manually verified that our Journald configuration don't grow more than 64M - https://github.com/PelionIoT/meta-pelion-edge/blob/dev/recipes-core/systemd/systemd-conf/journald.conf#L5 
`journalctl --disk-usage` reports 72M but that is couting 8M of active journal file. So it never grows above 72M.
=> By default enabled persistent logging in journald - prerequiste for FSS feature

recipes-wigwag/edge-proxy/files/launch-edge-proxy.sh
This is a patch to disable all the logs of edge-proxy until logging levels are implemented.
=> By default, disabled Edge proxy logs and added command to help debugger on how to enable the logs

recipes-containers/kubelet/files/launch-kubelet.sh
As kubelet service only look for `Wants=edge-proxy.service` and not `wait-for-pelion-identity`, it starts before identity.json is populated. Once Kubelet starts with deviceID=null, it throws error `node="null" not found` but doesn't exit. Hence, kubelet needs to be manually restarted after identity.json file is written and that's why we need 2 reboots for kubelet to register the node.
=> Do not start kubelet when deviceID is null

recipes-connectivity/identity-tool/identity-tool_0.0.1.bb, recipes-containers/kubelet/kubelet_git.bb, recipes-misc/info-tool/info-tool_2.0.0.bb
jq is used by kubelet, edge-proxy and identity-tool.
This fixes the regression issue in identity-tool - endpoint-name is set as serial number in identity file
=> Upgraded pe-util to 2.0.4 and added jq as RDEPENDS for services which are dependent on it

recipes-wigwag/maestro/maestro/imx8mmevk/devicedb.template.conf, recipes-wigwag/maestro/maestro/imx8mmevk/maestro-config-imx8mmevk.yaml
Added gateway_capabilites. Removed container templates and unused var_defs, configured devicedb to communicate via edge-proxy.
We are no longer generating self-signed certs on the gateway and devicedb configuration is trying to source the certs. Updated Devicedb configuration to use edge-proxy rather than directly establish a connection with Pelion Cloud.
=> Updated imx8 maestro and devicedb configuration

recipes-wigwag/maestro/maestro/uz3eg/devicedb.template.conf, recipes-wigwag/maestro/maestro/uz3eg/maestro-config-uz3eg.yaml
Added gateway_capabilites. Removed container templates and unused var_defs, configured devicedb to communicate via edge-proxy.
This could be why devicedb is failing on the Xilinx board. We are no longer generating self-signed certs on the gateway and devicedb configuration is trying to source the certs. Updated Devicedb configuration to use edge-proxy rather than directly establish a connection with Pelion Cloud. Maestro could be continuously restarting devicedb and not cleanly freeing up the file descriptor, eventually running out of it and cause panic.
=> Updated uz3eg platform maestro configuration

recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
`manifest-pelion-edge` nightly builds on `master` started failing a few days ago when pip dropped support and backwards compatability for Python 2.
However, `mbed_fcc` was still always pulling the latest version of pip before downgrading. This caused it to pull an incompatible version and fail to build, with even the error handler failing to to the syntax change.
Fortunately, the pypa.io maintainers were kind enough to include a way to pull a specific version, which is all this commit does.
=> [MERGE FOR HOTFIX] Fixed regression introduced due to Py2 support being officially dropped.

recipes-extended/fluentbit/files/td-agent-bit.conf, recipes-wigwag/maestro/maestro/imx8mmevk/maestro-config-imx8mmevk.yaml, recipes-wigwag/maestro/maestro/rpi3/maestro-config-rpi3bplus.yaml
This disables greaselib library being called in maestro. Might resolve the panic we are observing on imx8 board - Fatal error: sweep increased allocation count.
=> Disabled maestro logging and removed the tail filter from fluenbit

meta-lmp-support/recipes-core/images/console-image-lmp.bb
The issues with nodejs are now fixed, and the relay-term can be re-introduced
=> Add relay-term to the lmp-image

recipes-wigwag/maestro/maestro/imx8mmevk/0003-build-with-autoconf.patch, recipes-wigwag/maestro/maestro_0.0.1.inc
Not all the build devices are necessarily aarch64-linux devices, this PR fixes possible issues arising from the assumptions of the patch
TARGET_SYS documented here:
https://www.yoctoproject.org/docs/2.0.2/ref-manual/ref-manual.html#var-TARGET_SYS
=> Generalize the patch libuv autoconf patch

conf/local.conf.sample, recipes-connectivity/identity-tool/identity-tool_0.0.1.bb, recipes-containers/kubelet/kubelet_git.bb, recipes-misc/info-tool/info-tool_2.0.0.bb
Some customers has reported that they are unable to build meta-pelion-edge
as their corporate firewall only allows outbound HTTP/HTTPS but not SSH. This
should help with that use case.
=> Updated identity,kubelet & info source file protocol from ssh to https

meta-lmp-support/recipes-bsp/u-boot/u-boot-fio/uz/0001-Read-MAC-from-EEPROM-on-Xilinx.patch
Add a support patch to read MAC from EEPROM on the Xilinx/AVNET ZU3EG board.
The patch is not applied by default, and it should be used only when EEPROM has been written with a valid MAC address.
To apply patch at LmP root folder: `git -C layers/meta-lmp am ../meta-pelion-edge/meta-lmp-support/recipes-bsp/u-boot/u-boot-fio/uz/0001-Read-MAC-from-EEPROM-on-Xilinx.patch`
=> Add a support patch to read MAC from EEPROM on Xilinx/AVNET ZU3EG board

recipes-wigwag/mbed-fcc/mbed-fcc_0.0.1.bb
If not exported, these dont propagate to the pip3 or python3
=> Export proxy values

meta-lmp-support/recipes-core/images/console-image-lmp.bb
There may be more, but these were the ones that I could remove with a quick test
=> Remove unnecessary foundries.io includes

meta-lmp-support/recipes-bsp/device-tree/device-tree.bbappend, meta-lmp-support/recipes-bsp/device-tree/files/uz3eg-iocc/Read-EMAC-from-EEPROM-on-uz3eg-iocc.patch
Remove fixed EMAC address from device-tree and read it from EEPROM.
Tested on an AES-ZU3EG-1-SK-G evaluation board.
Without this change:
```
Warning: ethernet@ff0e0000 using MAC address from DT
ZynqMP> printenv ethaddr
ethaddr=00:0a:35:00:02:90
```
With this change and EEPROM UNinitialized:
```
Warning: ethernet@ff0e0000 (eth0) using random MAC address - c2:d0:ec:05:1d:af
```
Write MAC on EEPROM:
```
Hit any key to stop autoboot:  0
ZynqMP> i2c dev 2
Setting bus to 2
ZynqMP> mm.b 0
00000000: 60 ? 12
00000001: 09 ? 34
00000002: 00 ? 56
00000003: 20 ? 78
00000004: 00 ? 9a
00000005: 00 ? bc
00000006: 00 ? q
ZynqMP> i2c write 0 51 20 6
ZynqMP> reset
...
Warning: ethernet@ff0e0000 using MAC address from ROM
```
=> Read EMAC from EEPROM on uz3eg-iocc

meta-lmp-support/wic/sdimage-uz-sota-config.wks.in
Comment referes to i.MX8, but really this file is for the AVNET ZU3EG.
=>  sdimage-zu3 - fix comment on target

meta-lmp-support/conf/machine/include/lmp-factory-custom.inc, meta-lmp-support/recipes-core/base-files/base-files/rpi/fstab, meta-lmp-support/wic/sdimage-rpi3-spl-sota-config.wks.in, recipes-bsp/bootfiles/rpi-config_git.bbappend, recipes-wigwag/maestro/maestro-rpi3.bb
Raspberry Pi3/4 support. Thanks to Kimmo for finding that one missing piece and verifying the RPI4B.
This change more or less generalizes the current RPI3 support for all Raspberries, as the changes are not actually board specific.
Full functionality requires also changes in meta-mbed-edge, see PR https://github.com/PelionIoT/meta-mbed-edge/pull/47.
=> LmP RaspberryPi3/4 support

meta-lmp-support/recipes-core/base-files/base-files/imx8mmevk/fstab, meta-lmp-support/recipes-core/base-files/base-files/uz/fstab
Use LABELs instead of mmcblocks - they are  pain the back to maintain/figure out. LABELs are portable, more abstract and are more likely to remain the same even if the partitioning changes a bit. The `fstab` file is likely going to be 100% same for all the targets this way.
=> Use LABELs in fstab

meta-lmp-support/recipes-core/images/console-image-lmp.bb
Testing team needs `nmcli` so replacing `nmtui` with it.
=> Replace nmtui with nmcli

meta-lmp-support/conf/machine/include/lmp-factory-custom.inc, recipes-bsp/bootfiles/rpi-config_git.bbappend
another way to fix ble for raspberry is just to use default console settings instead of hardcoding console=ttyAMA0 for serial console.
=> Use standard tty config, fixes ble

recipes-bsp/bootfiles/rpi-config_git.bbappend
starts using miniuart-bt as default overlay as we are reserving main uart for serial command line.
=> use miniuart bt dtoverlay to enable bluetooth again

meta-lmp-support/conf/machine/include/lmp-factory-custom.inc, recipes-bsp/bootfiles/rpi-config_git.bbappend
test7 for rasp was failing and seemed to pass with these changes in https://github.com/PelionIoT/manifest-lmp-pelion-edge/pull/35 which pointed to this PR's hash in git.
=> Raspberry issue testing ci

recipes-core/netbase/netbase/hosts, recipes-wigwag/edge-proxy/files/launch-edge-proxy.sh
1. Modify edge-proxy config to add new forwarding address for containers domain
2. Add `containers.local` to the list of known hosts
=> Add local host and forward address for container domain

meta-imx8mmsolidrun-support/recipes-kernel/linux-firmware/linux-firmware-cyw-bt-patch-bcm43455_git.bb, meta-imx8mmsolidrun-support/recipes-kernel/linux-firmware/linux-firmware-cyw-fmac-fw-bcm43455-sdio_git.bb, meta-imx8mmsolidrun-support/recipes-kernel/linux-firmware/linux-firmware-cyw-fmac-nvram-bcm43455-sdio_git.bb, meta-lmp-support/conf/machine/include/lmp-factory-custom.inc
Foundries commits f2fb8571bc4084b15fb6a73edf6965ecc363f405 and 62f03ea2eb9063c94966fcbd3525d75cc2e67990
=> Avoid conflict in other layers with firmware recipes

recipes-extended/ostree/ostree/update-default-grub-cfg-header.patch, recipes-extended/ostree/ostree_%.bbappend
Copies foundries.io ostree modifications to ensure changes are compiled into the build.
=> sets ostree's branch to main as master removed and broke the build.

recipes-wigwag/mbed-fcce/mbed-fcce/0001-fix-arm_uc_pal_linux_extensions.manual_patch, recipes-wigwag/mbed-fcce/mbed-fcce/0001-fix-mcc_common_setup.manual_patch, recipes-wigwag/mbed-fcce/mbed-fcce_4.9.0.bb
Reintroduced patches for building with PARSEC_TPM_SE_SUPPORT.
=> Fix the build when MBED_EDGE_CORE_CONFIG_PARSEC_TPM_SE_SUPPORT = ON.

meta-lmp-support/recipes-bsp/u-boot/u-boot-xlnx_%.bbappend
Fix for CI on Xilinx machines to enforce deploy before install, see note of do_deploy at https://docs.yoctoproject.org/current/overview-manual/concepts.html#shared-state
=> Enforce deploy before install on uz machines

meta-lmp-support/recipes-security/optee/optee-os-fio_3.10.0.bbappend
Disable trace messages from the trusted application.
On the imx boards choose not to use the CRYPTO_DRIVER as is does not
correctly support variable length buffers used by the PARSEC PKCS11
provider.
=> Override optee recipe for PKCS11 support.

meta-lmp-support/conf/machine/include/lmp-factory-custom.inc
Set so all boards use SOFTWARE_TPM by default.
Provide specific overrides for:
- The mx8 uses PKCS11
- The uz uses PKCS11
- The rpi uses SOFTWARE_TPM (not strictly necessary, but is consistent)
=> Set PARSEC_PROVIDER per device type.

meta-lmp-support/recipes-security/optee/files/0001-optee.patch, meta-lmp-support/recipes-security/optee/optee-os-fio_3.10.0.bbappend
The optee_os RSA decrypt code used on imx devices does not correctly
support varialble length buffers. This patch returns the length of
buffer required to support the decrypt when passed a null pointer.
=> Patch optee for pkcs11_decrypt.

meta-lmp-support/recipes-kernel/linux/files/xilinx_cpu_idle.cfg, meta-lmp-support/recipes-kernel/linux/files/xilinx_rcu_boost.cfg, meta-lmp-support/recipes-kernel/linux/linux-lmp-xlnx_git.bbappend
This reverts commit 6acc5b204b651482695400a58f7314265e6e7096.
For some reason we have stability issues with the latest dev on AVNET ZU3-EG.
=> Revert "Enable PREEMPT with RCU boost"

meta-lmp-support/recipes-core/images/initramfs-ostree-lmp-image.bbappend, meta-lmp-support/recipes-core/initrdscripts/initramfs-framework/ostreecheck, meta-lmp-support/recipes-core/initrdscripts/initramfs-framework_%.bbappend
Addition of OSTree fsck+diff to initramfs for LMP builds.
Currently unconditional - this adds complete ostree to initramfs, potentially increasing its size by 10MB.
Check pass/failure are only logged. The "fatal" directives that would enforce it are commented out.
=> First pass at OSTree diff/fsck

meta-lmp-support/conf/machine/include/lmp-factory-custom.inc
We don't want LMP builds to perform their standard auto-push to a server. Leaving variables unset is sufficient, but generates a warning. Disable the relevant entries in IMAGE_FSTYPES to also suppress the warning.
=> Disable LMP ostreepush+garagesign+garagecheck

recipes-connectivity/coredns/coredns_1.8.3.bb, recipes-connectivity/coredns/files/coredns-starter.service, recipes-connectivity/coredns/files/coredns-starter.sh, recipes-connectivity/coredns/files/coredns.service
Currently, coredns is producing a lot of redundant logs, as the service is dependent on kube-bridge network interface and constantly restarts when this is not available.
This PR adds a script that monitors the kube-bridge interface and only starts up the coredns service when it's available.
Furthermore, systemd.path cannot be used as the network-related files are in /sys/.. which are not regular 'files'. Modifications do not trigger service listeners.
=> coredns watcher service

meta-lmp-support/recipes-core/initrdscripts/initramfs-framework/ostreecheck
OSTree script is failing due to the presence of /run/ostree-booted
in initramfs.
Issue raised at
https://github.com/ostreedev/ostree/issues/2485
Delete /run/ostree-booted from initramfs to make it work.
Also remove some stray debugging.
=> Fix OSTree check

meta-lmp-support/recipes-core/images/console-image-lmp.bb
By adding the parsec group the the ETC_GROUP_MEMBERS variable, a new user can have the parsec group added.
e.g.
sudo useradd -G parsec -e $(date --date='1 week' --rfc-3339=date) -u 1250 bob
will allow user bob to access parsec services.
See also https://github.com/foundriesio/meta-lmp/pull/408
=> Add the parsec group to ETC_GROUP_MEMBERS

recipes-containers/kubelet/files/launch-kubelet.sh
Verbose level 1 was still not enough, remove verbose completely.
There is still quite a lot of logs, example attached.
[journalctl.log](https://github.com/PelionIoT/meta-pelion-edge/files/7606495/journalctl.log)
=> Remove kube verbose logs

recipes-containers/kube-router/files/launch-kube-router.sh
OSTree check fails due to modified `/wigwag/system/etc/cni/net.d/10-kuberouter.conflist`. As kube-router needs to modify this file during runtime, make a copy in the `/run` directory and point kube-router to the copy.
The config file only holds state during runtime and can be reset when the device is rebooted.
=> Change location of kube-router config to fix OSTree fail

recipes-containers/kubelet/kubelet_git.bb
It is still referring to legacy domain.
=> kubelet.git -> refer to PelionIoT

recipes-wigwag/mbed-fcce/mbed-fcce_4.11.1.bb
Still referring to armmbed, should be PelionIoT.
=> FCCE domain fix to recipe

meta-lmp-support/recipes-containers/runc/runc-opencontainers_git.bbappend
The https://github.com/opencontainers/runc master branch has been
renamed to main.
https://github.com/opencontainers/runc/issues/3250
This bbappend changes the SRC_URI to use main, and overrides the default
in https://github.com/foundriesio/meta-lmp/blob/23c85c11395dddf1ed975bc30aa3ad76927024d8/meta-lmp-base/recipes-containers/runc/runc-opencontainers_git.bb
=> Hotfix for opencontainers/runc branch rename.

CHANGELOG.md, recipes-misc/info-tool/info-tool_2.0.0.bb, recipes-misc/testnet/testnet_2.0.0.bb
`info` tool gets updated for real, `testnet.sh` just cosmetically.
=> Update pe-utils to v 2.0.12
